# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      
    #Install packages
    - name: Install packages
      run: npm install --save katalon-studio/katalon-agent#v1.4.0

    # Runs Katalon Studio Action
    - name: Runs Katalon Studio Action Step
      uses: ./ #Uses an action in the root directory
      with:
          theksVersion: '7.5.5'
          theksLocation: ''
          theksProjectPath: $GITHUB_WORKSPACE/simple_project/simple_project
          theksArgs: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Run All Test Suites" -apiKey="fdb89052-b651-46fe-ac7c-b7b4b305eb55" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY'
          thex11Display: ''
          xvfbConfiguration: ''
